name: Build site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build the site
    image: alpine:latest
    #runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Download Zola
        run: |
          # Install the zola package from the alpine community repositories
          apk add --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ zola

      - name: Build
        run: |
          ./zola build
